### ISSUE TITLE
Login (JWT)

### ISSUE THREAD

**Issue by DavidVasilev1** [CSA-Tri-1/projectTri1#9]
#### Login Page (tentative)
> Generic login page for users to document their scores from the game element

- [x] Have login page, generic
- [x] Sending data to backend for registration and pulling data from backend to log user scores
Optional:
- [x] JWT or Firebase

#### Leaderboard Page (tentative)
> Display all data from the users, including score and name

- [x] Pull data from backend, displaying data with jQuery

**Comment by drewreed2005** [comment]
### Update

- Leaderboard page has been removed
- Backend login works well
- [x] Connect login to backend
